import Vue from 'vue'
import { Button, Field, Icon, Tabbar, TabbarItem, Swipe, SwipeItem, Overlay, Tab, Tabs, Dialog, Form, Toast, TreeSelect, Search, PullRefresh, ActionSheet, Cell, List, RadioGroup, Radio, Loading, GoodsAction, GoodsActionButton, GoodsActionIcon, DropdownMenu, DropdownItem, Popup, Collapse, CollapseItem, NavBar, switchCell, sku, shareSheet, ImagePreview, Col, Row, Stepper, Checkbox, CheckboxGroup, Calendar, DatetimePicker, AddressEdit, AddressList, Notify, Card, Tag } from 'vant';

Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(Button);
Vue.use(Field)
Vue.use(Icon)
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Overlay);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Form);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Toast);
Vue.use(TreeSelect);
Vue.use(Dialog);
Vue.use(Search);
Vue.use(PullRefresh);
Vue.use(ActionSheet);
Vue.use(Cell);
Vue.use(List);
Vue.use(Loading);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
Vue.use(ImagePreview)
Vue.use(sku)
Vue.use(Collapse);
Vue.use(CollapseItem);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Popup)
Vue.use(switchCell)
Vue.use(NavBar)
Vue.use(shareSheet)
Vue.use(Stepper)
Vue.use(Col);
Vue.use(Row);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Calendar)
Vue.use(DatetimePicker)
Vue.use(AddressEdit)
Vue.use(AddressList)
Vue.use(Notify)
Vue.use(Card)
Vue.use(Tag)